language: ruby
rvm:
  - 2.3.5
  - 2.4.2
  - 2.2.7
  - ruby-head
  - jruby-head

sudo: false
before_install: gem install bundler -v 1.16.0
cache: bundler
bundler_args: --binstubs
script:
  - bin/rubocop
  - bin/rspec
