language: ruby
sudo: false
before_install: gem install bundler
cache: bundler
script: bundle exec rspec
matrix:
  fast_finish: true
  include:
    - rvm: 2.2.10
      gemfile: gemfiles/with_native_extensions.gemfile
      env: TEST_NATIVE_EXTENSIONS=true
    - rvm: 2.3.7
      gemfile: gemfiles/with_native_extensions.gemfile
      env: TEST_NATIVE_EXTENSIONS=true
    - rvm: 2.4.4
      gemfile: gemfiles/with_native_extensions.gemfile
      env: TEST_NATIVE_EXTENSIONS=true
    - rvm: 2.5.1
      gemfile: gemfiles/with_native_extensions.gemfile
      env: TEST_NATIVE_EXTENSIONS=true
    - rvm: ruby-head
      gemfile: gemfiles/with_native_extensions.gemfile
      env: TEST_NATIVE_EXTENSIONS=true
    - rvm: 2.2.10
      gemfile: gemfiles/without_native_extensions.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/without_native_extensions.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/without_native_extensions.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/without_native_extensions.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/without_native_extensions.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/without_native_extensions.gemfile
