# frozen_string_literal: true

module EvilEvents::Core
  # @api private
  # @since 0.1.0
  module Events
    require_relative 'events/serializers'
    require_relative 'events/serializers/base'
    require_relative 'events/serializers/hash'
    require_relative 'events/serializers/json'
    require_relative 'events/event_extensions/type_aliasing'
    require_relative 'events/event_extensions/payloadable'
    require_relative 'events/event_extensions/payloadable/abstract_payload'
    require_relative 'events/event_extensions/manageable'
    require_relative 'events/event_extensions/adapter_customizable'
    require_relative 'events/event_extensions/observable'
    require_relative 'events/event_extensions/serializable'
    require_relative 'events/event_extensions/metadata_extendable'
    require_relative 'events/event_extensions/metadata_extendable/abstract_metadata'
    require_relative 'events/event_extensions/emittable'
    require_relative 'events/event_extensions/class_signature'
    require_relative 'events/event_extensions/class_signature/signature'
    require_relative 'events/event_extensions/class_signature/equalizer'
    require_relative 'events/event_extensions/hookable'
    require_relative 'events/event_extensions/hookable/abstract_hook'
    require_relative 'events/event_extensions/hookable/after_emit_hook'
    require_relative 'events/event_extensions/hookable/before_emit_hook'
    require_relative 'events/event_extensions/hookable/on_error_hook'
    require_relative 'events/notifier'
    require_relative 'events/notifier/logging'
    require_relative 'events/notifier/abstract'
    require_relative 'events/notifier/sequential'
    require_relative 'events/notifier/worker'
    require_relative 'events/notifier/worker/executor'
    require_relative 'events/notifier/worker/job'
    require_relative 'events/notifier/builder'
    require_relative 'events/abstract_event'
    require_relative 'events/manager'
    require_relative 'events/manager/subscriber_list'
    require_relative 'events/manager_factory'
    require_relative 'events/manager_registry'
    require_relative 'events/subscriber'
    require_relative 'events/subscriber/mixin'
    require_relative 'events/event_factory'
  end
end
